language: node_js
node_js:
  - 12.18.0
cache: yarn

install:
  - yarn install

directories:
    - node_modules

script:
  - yarn test
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: gh-pages
