language: node_js
node_js:
  - 12.18.1
cache: npm

install:
  - npm install

directories:
    - node_modules

script:
  - npm test
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: build
  github-token: $GITHUB_TOKEN
  on:
    branch: atualizacoes
